easy_admin:
  disabled_actions: ['show']
  site_name: Meloven Dashboard
  design:
    menu:
      - User
      - BlogPost
      - Event
      - Photo
  list:
    title: 'Liste des %%entity_label%%'
    actions: ['show']
  entities:
    User:
      class: App\Entity\User
      controller: App\Controller\Admin\EasyAdmin\UserController
      export_path: '%kernel.root_dir/../var/export/user'
      password_encoding: { algorithm: 'bcrypt', cost: 12 }
      label: 'Utilisateurs'
      help: 'Un utilisateur peut être ADMIN ou USER.'
      list:
        title: 'Liste des utilisateurs'
        fields:
          - { property: username, label: 'Username' }
          - { property: firstName, label: 'Prénom' }
          - { property: lastName, label: 'Nom' }
          - email
          - { property: avatar, label: 'Photo', type: image, base_path: '/media/' }
          - { property: isActive, label: 'Actif' }
          - { property: isAdmin, label: 'Admin' }
          - { property: userGroup, label: 'User Group' }
      form:
        fields:
          - { property: username, label: 'Username' }
          - { property: firstName, label: 'Prénom' }
          - { property: lastName, label: 'Nom' }
          - { property: userdescription, type: 'ckeditor' }
          - { property: location, label: "Localisation de l'artiste" }
          - { property: facebook, label: 'Facebook' }
          - { property: youtube, label: 'Youtube' }
          - { property: twitter, label: 'Twitter' }
          - { property: instagram, label: 'Instagram' }
          - { property: plainPassword, label: 'Mot de passe', type: 'password' }
          - { property: email, label: 'Adresse email' }
          - { property: avatarFile, label: 'Photo de profil', type: 'vich_image' }
          - { property: backgroundImageFile, label: 'Photo fond, page profil', type: 'vich_image' }
          - { property: photos, label: 'Gallery de photos' }
          - { property: isActive, label: 'Actif' }
          - { property: isAdmin, label: 'Admin' }
          - { property: videos, label: 'Videos' }
          - { property: userGroup, type: choice, type_options: {choices: {'Admin':'Admin', 'Musician':'Musician', 'Author':'Author'}}}
    BlogPost:
      class: App\Entity\BlogPost
      label: 'BlogPost'
      list:
        title: 'Liste des Post'
        fields:
          - id
          - Title
    Event:
      class: App\Entity\Event
      label: 'Events list'
      list:
        title: 'Event'
        fields:
          - id
          - Title
      form:
        fields:
          - { property: title, label: 'Titre' }
          - { property: organizer, label: 'Organisateur' }
          - { property: adress, label: 'Adresse' }
          - { property: date, label: 'Date'}
          - { property: hour, label: "Heure de l'évenement" }
          - { property: description, label: 'Description', type: 'ckeditor' }
          - { property: user, label: 'Actif' }
          - { property: btnName, label: 'Nom du bouton' }
          - { property: btnUrl, label: 'Url du bouton' }
    Photo:
      class: App\Entity\Photo
      label: 'Photo'
      list:
        title: 'Liste des photos'
        fields:
          - id
          - { property: photo, label: 'Photo', type: image, base_path: '/media/' }
          - { property: user, label: 'User'}
      form:
        fields:
          - { property: photoFile, label: 'Photo', type: 'vich_image'}
          - { property: user, label: 'User', type_options: { by_reference: false }}