<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvjqjks\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvjqjks/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVvjqjks.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerVvjqjks\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerVvjqjks\srcProdProjectContainer(array(
    'container.build_hash' => 'Vvjqjks',
    'container.build_id' => 'ef0eaa3e',
    'container.build_time' => 1530638545,
));
