<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\BlogPostController:index' => function () {
    return ${($_ = isset($this->services['service_locator.x1re6u6']) ? $this->services['service_locator.x1re6u6'] : $this->load(__DIR__.'/getServiceLocator_X1re6u6Service.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:artiste' => function () {
    return ${($_ = isset($this->services['service_locator.gzbqeat']) ? $this->services['service_locator.gzbqeat'] : $this->load(__DIR__.'/getServiceLocator_GzbqeatService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:blog' => function () {
    return ${($_ = isset($this->services['service_locator.mtkdrqx']) ? $this->services['service_locator.mtkdrqx'] : $this->load(__DIR__.'/getServiceLocator_MtkdrqxService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:home' => function () {
    return ${($_ = isset($this->services['service_locator.hcf6d98']) ? $this->services['service_locator.hcf6d98'] : $this->load(__DIR__.'/getServiceLocator_Hcf6d98Service.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:listPostsByCategory' => function () {
    return ${($_ = isset($this->services['service_locator.mtkdrqx']) ? $this->services['service_locator.mtkdrqx'] : $this->load(__DIR__.'/getServiceLocator_MtkdrqxService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:listeDesArtiste' => function () {
    return ${($_ = isset($this->services['service_locator.gzbqeat']) ? $this->services['service_locator.gzbqeat'] : $this->load(__DIR__.'/getServiceLocator_GzbqeatService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:mentionsLegales' => function () {
    return ${($_ = isset($this->services['service_locator.mtkdrqx']) ? $this->services['service_locator.mtkdrqx'] : $this->load(__DIR__.'/getServiceLocator_MtkdrqxService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:show' => function () {
    return ${($_ = isset($this->services['service_locator.p.opqgd']) ? $this->services['service_locator.p.opqgd'] : $this->load(__DIR__.'/getServiceLocator_P_OpqgdService.php')) && false ?: '_'};
}, 'App\\Controller\\SecurityController:login' => function () {
    return ${($_ = isset($this->services['service_locator.kakbubj']) ? $this->services['service_locator.kakbubj'] : $this->load(__DIR__.'/getServiceLocator_KakbubjService.php')) && false ?: '_'};
}, 'App\\Controller\\SecurityController:register' => function () {
    return ${($_ = isset($this->services['service_locator.x2iwyq0']) ? $this->services['service_locator.x2iwyq0'] : $this->load(__DIR__.'/getServiceLocator_X2iwyq0Service.php')) && false ?: '_'};
}, 'App\\Controller\\BlogPostController::index' => function () {
    return ${($_ = isset($this->services['service_locator.x1re6u6']) ? $this->services['service_locator.x1re6u6'] : $this->load(__DIR__.'/getServiceLocator_X1re6u6Service.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::artiste' => function () {
    return ${($_ = isset($this->services['service_locator.gzbqeat']) ? $this->services['service_locator.gzbqeat'] : $this->load(__DIR__.'/getServiceLocator_GzbqeatService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::blog' => function () {
    return ${($_ = isset($this->services['service_locator.mtkdrqx']) ? $this->services['service_locator.mtkdrqx'] : $this->load(__DIR__.'/getServiceLocator_MtkdrqxService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::home' => function () {
    return ${($_ = isset($this->services['service_locator.hcf6d98']) ? $this->services['service_locator.hcf6d98'] : $this->load(__DIR__.'/getServiceLocator_Hcf6d98Service.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::listPostsByCategory' => function () {
    return ${($_ = isset($this->services['service_locator.mtkdrqx']) ? $this->services['service_locator.mtkdrqx'] : $this->load(__DIR__.'/getServiceLocator_MtkdrqxService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::listeDesArtiste' => function () {
    return ${($_ = isset($this->services['service_locator.gzbqeat']) ? $this->services['service_locator.gzbqeat'] : $this->load(__DIR__.'/getServiceLocator_GzbqeatService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::mentionsLegales' => function () {
    return ${($_ = isset($this->services['service_locator.mtkdrqx']) ? $this->services['service_locator.mtkdrqx'] : $this->load(__DIR__.'/getServiceLocator_MtkdrqxService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::show' => function () {
    return ${($_ = isset($this->services['service_locator.p.opqgd']) ? $this->services['service_locator.p.opqgd'] : $this->load(__DIR__.'/getServiceLocator_P_OpqgdService.php')) && false ?: '_'};
}, 'App\\Controller\\SecurityController::login' => function () {
    return ${($_ = isset($this->services['service_locator.kakbubj']) ? $this->services['service_locator.kakbubj'] : $this->load(__DIR__.'/getServiceLocator_KakbubjService.php')) && false ?: '_'};
}, 'App\\Controller\\SecurityController::register' => function () {
    return ${($_ = isset($this->services['service_locator.x2iwyq0']) ? $this->services['service_locator.x2iwyq0'] : $this->load(__DIR__.'/getServiceLocator_X2iwyq0Service.php')) && false ?: '_'};
})));
