<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.gzbqeat' shared service.

return $this->services['service_locator.gzbqeat'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('userRepository' => function () {
    $f = function (\App\Repository\UserRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\UserRepository']) ? $this->services['App\Repository\UserRepository'] : $this->load(__DIR__.'/getUserRepositoryService.php')) && false ?: '_'});
}));
