<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Welp\MailchimpBundle\Command\SynchronizeSubscribersCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Command/SynchronizeSubscribersCommand.php';

$this->services['Welp\MailchimpBundle\Command\SynchronizeSubscribersCommand'] = $instance = new \Welp\MailchimpBundle\Command\SynchronizeSubscribersCommand();

$instance->setName('welp:mailchimp:synchronize-subscribers');

return $instance;
