<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.p.opqgd' shared service.

return $this->services['service_locator.p.opqgd'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('blogPostRepository' => function () {
    $f = function (\App\Repository\BlogPostRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\BlogPostRepository']) ? $this->services['App\Repository\BlogPostRepository'] : $this->load(__DIR__.'/getBlogPostRepositoryService.php')) && false ?: '_'});
}));
