<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Welp\MailchimpBundle\Command\SynchronizeMergeFieldsCommand' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Command/ContainerAwareCommand.php';
include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Command/SynchronizeMergeFieldsCommand.php';

$this->services['Welp\MailchimpBundle\Command\SynchronizeMergeFieldsCommand'] = $instance = new \Welp\MailchimpBundle\Command\SynchronizeMergeFieldsCommand();

$instance->setName('welp:mailchimp:synchronize-merge-fields');

return $instance;
