<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'welp_mailchimp.mailchimp_master' shared service.

include_once $this->targetDirs[3].'/vendor/drewm/mailchimp-api/src/MailChimp.php';

return $this->services['welp_mailchimp.mailchimp_master'] = new \DrewM\MailChimp\MailChimp('a677ff9eac61440824f59d62abc0eace-us18');
