<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'welp_mailchimp.provider.factory' shared service.

include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Provider/ProviderFactory.php';

return $this->services['welp_mailchimp.provider.factory'] = new \Welp\MailchimpBundle\Provider\ProviderFactory($this);
