<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'welp_mailchimp.list_synchronizer' shared service.

include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Subscriber/ListSynchronizer.php';

return $this->services['welp_mailchimp.list_synchronizer'] = new \Welp\MailchimpBundle\Subscriber\ListSynchronizer(${($_ = isset($this->services['welp_mailchimp.list_repository']) ? $this->services['welp_mailchimp.list_repository'] : $this->load(__DIR__.'/getWelpMailchimp_ListRepositoryService.php')) && false ?: '_'});
