<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'welp_mailchimp.list_provider' shared service.

include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Provider/ListProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Provider/ConfigListProvider.php';
include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Provider/ProviderFactory.php';

return $this->services['welp_mailchimp.list_provider'] = new \Welp\MailchimpBundle\Provider\ConfigListProvider(${($_ = isset($this->services['welp_mailchimp.provider.factory']) ? $this->services['welp_mailchimp.provider.factory'] : $this->services['welp_mailchimp.provider.factory'] = new \Welp\MailchimpBundle\Provider\ProviderFactory($this)) && false ?: '_'}, array());
