<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'welp_mailchimp.subscriber_listener' shared service.

include_once $this->targetDirs[3].'/vendor/welp/mailchimp-bundle/src/Event/SubscriberListener.php';

return $this->services['welp_mailchimp.subscriber_listener'] = new \Welp\MailchimpBundle\Event\SubscriberListener(${($_ = isset($this->services['welp_mailchimp.list_repository']) ? $this->services['welp_mailchimp.list_repository'] : $this->load(__DIR__.'/getWelpMailchimp_ListRepositoryService.php')) && false ?: '_'});
